version: '2'
services:
    hanndbn-app:
        image: hanndbn
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hanndbn-postgresql:5432/hanndbn
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://hanndbn-elasticsearch:9200
        ports:
            - 8080:8080
    hanndbn-postgresql:
        extends:
            file: postgresql.yml
            service: hanndbn-postgresql
    hanndbn-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hanndbn-elasticsearch
