version: '2'
services:
    hanndbn-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/hanndbn/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hanndbn
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
