/*
Script generated by Aqua Data Studio 19.0.1-5 on Mar-15-2019 08:04:36 AM
Database: hanndbn
Schema: public
Objects: OBJECT_TYPE, DATATYPE, SEQUENCE, RULE, TABLE, VIEW, MAT_VIEW, PROCEDURE, FUNCTION, INDEX, TRIGGER
*/
ALTER TABLE "public"."jhi_user_authority"
	DROP CONSTRAINT "fk_user_id" CASCADE 
GO
ALTER TABLE "public"."jhi_user_authority"
	DROP CONSTRAINT "fk_authority_name" CASCADE 
GO
ALTER TABLE "public"."jhi_persistent_audit_evt_data"
	DROP CONSTRAINT "fk_evt_pers_audit_evt_data" CASCADE 
GO
ALTER TABLE "public"."jhi_user"
	DROP CONSTRAINT "ux_user_login" CASCADE 
GO
ALTER TABLE "public"."jhi_user"
	DROP CONSTRAINT "ux_user_email" CASCADE 
GO
DROP INDEX "public"."idx_persistent_audit_evt_data"
GO
DROP INDEX "public"."idx_persistent_audit_event"
GO
DROP TABLE "public"."shop_statistic"
GO
DROP TABLE "public"."shop"
GO
DROP TABLE "public"."jhi_user_authority"
GO
DROP TABLE "public"."jhi_user"
GO
DROP TABLE "public"."jhi_persistent_audit_evt_data"
GO
DROP TABLE "public"."jhi_persistent_audit_event"
GO
DROP TABLE "public"."jhi_authority"
GO
DROP TABLE "public"."item_statistic"
GO
DROP TABLE "public"."item"
GO
DROP TABLE "public"."databasechangeloglock"
GO
DROP TABLE "public"."databasechangelog"
GO
DROP TABLE "public"."category_statistic"
GO
DROP TABLE "public"."category"
GO

CREATE TABLE "public"."category"  ( 
	"id"              	bigint NOT NULL,
	"catid"           	bigint NOT NULL,
	"category_name"   	varchar(255) NULL,
	"display_name"    	varchar(255) NULL,
	"sort_weight"     	bigint NULL,
	"parent_category" 	bigint NULL,
	"is_adult"        	integer NULL,
	"create_date"     	timestamp NULL,
	"last_update_date"	timestamp NULL,
	CONSTRAINT "pk_category" PRIMARY KEY("id")
)
GO
ALTER TABLE "public"."category" OWNER TO "hanndbn"
GO
CREATE TABLE "public"."category_statistic"  ( 
	"id"              	bigint NOT NULL,
	"catid"           	bigint NOT NULL,
	"sort_weight"     	bigint NULL,
	"create_date"     	timestamp NULL,
	"last_update_date"	timestamp NULL,
	CONSTRAINT "pk_category_statistic" PRIMARY KEY("id")
)
GO
ALTER TABLE "public"."category_statistic" OWNER TO "hanndbn"
GO
CREATE TABLE "public"."databasechangelog"  ( 
	"id"           	varchar(255) NOT NULL,
	"author"       	varchar(255) NOT NULL,
	"filename"     	varchar(255) NOT NULL,
	"dateexecuted" 	timestamp NOT NULL,
	"orderexecuted"	integer NOT NULL,
	"exectype"     	varchar(10) NOT NULL,
	"md5sum"       	varchar(35) NULL,
	"description"  	varchar(255) NULL,
	"comments"     	varchar(255) NULL,
	"tag"          	varchar(255) NULL,
	"liquibase"    	varchar(20) NULL,
	"contexts"     	varchar(255) NULL,
	"labels"       	varchar(255) NULL,
	"deployment_id"	varchar(10) NULL 
	)
GO
ALTER TABLE "public"."databasechangelog" OWNER TO "postgres"
GO
CREATE TABLE "public"."databasechangeloglock"  ( 
	"id"         	integer NOT NULL,
	"locked"     	boolean NOT NULL,
	"lockgranted"	timestamp NULL,
	"lockedby"   	varchar(255) NULL,
	CONSTRAINT "pk_databasechangeloglock" PRIMARY KEY("id")
)
GO
ALTER TABLE "public"."databasechangeloglock" OWNER TO "postgres"
GO
CREATE TABLE "public"."item"  ( 
	"id"              	bigint NOT NULL,
	"itemid"          	bigint NOT NULL,
	"name"            	varchar(255) NULL,
	"catid"           	bigint NULL,
	"status"          	integer NULL,
	"create_date"     	timestamp NULL,
	"last_update_date"	timestamp NULL,
	CONSTRAINT "pk_item" PRIMARY KEY("id")
)
GO
ALTER TABLE "public"."item" OWNER TO "hanndbn"
GO
CREATE TABLE "public"."item_statistic"  ( 
	"id"              	bigint NOT NULL,
	"itemid"          	bigint NOT NULL,
	"liked_count"     	bigint NULL,
	"historical_sold" 	bigint NULL,
	"sold"            	bigint NULL,
	"view_count"      	bigint NULL,
	"rating_count"    	varchar(255) NULL,
	"rating_star"     	real NULL,
	"create_date"     	timestamp NULL,
	"last_update_date"	timestamp NULL,
	CONSTRAINT "pk_item_statistic" PRIMARY KEY("id")
)
GO
ALTER TABLE "public"."item_statistic" OWNER TO "hanndbn"
GO
CREATE TABLE "public"."jhi_authority"  ( 
	"name"	varchar(50) NOT NULL,
	CONSTRAINT "pk_jhi_authority" PRIMARY KEY("name")
)
GO
ALTER TABLE "public"."jhi_authority" OWNER TO "postgres"
GO
CREATE TABLE "public"."jhi_persistent_audit_event"  ( 
	"event_id"  	bigint NOT NULL,
	"principal" 	varchar(50) NOT NULL,
	"event_date"	timestamp NULL,
	"event_type"	varchar(255) NULL,
	CONSTRAINT "pk_jhi_persistent_audit_event" PRIMARY KEY("event_id")
)
GO
ALTER TABLE "public"."jhi_persistent_audit_event" OWNER TO "postgres"
GO
CREATE TABLE "public"."jhi_persistent_audit_evt_data"  ( 
	"event_id"	bigint NOT NULL,
	"name"    	varchar(150) NOT NULL,
	"value"   	varchar(255) NULL,
	PRIMARY KEY("event_id","name")
)
GO
ALTER TABLE "public"."jhi_persistent_audit_evt_data" OWNER TO "postgres"
GO
CREATE TABLE "public"."jhi_user"  ( 
	"id"                	bigint NOT NULL,
	"login"             	varchar(50) NOT NULL,
	"password_hash"     	varchar(60) NOT NULL,
	"first_name"        	varchar(50) NULL,
	"last_name"         	varchar(50) NULL,
	"email"             	varchar(191) NULL,
	"image_url"         	varchar(256) NULL,
	"activated"         	boolean NOT NULL,
	"lang_key"          	varchar(6) NULL,
	"activation_key"    	varchar(20) NULL,
	"reset_key"         	varchar(20) NULL,
	"created_by"        	varchar(50) NOT NULL,
	"created_date"      	timestamp NULL,
	"reset_date"        	timestamp NULL,
	"last_modified_by"  	varchar(50) NULL,
	"last_modified_date"	timestamp NULL,
	CONSTRAINT "pk_jhi_user" PRIMARY KEY("id")
)
GO
ALTER TABLE "public"."jhi_user" OWNER TO "postgres"
GO
CREATE TABLE "public"."jhi_user_authority"  ( 
	"user_id"       	bigint NOT NULL,
	"authority_name"	varchar(50) NOT NULL,
	PRIMARY KEY("user_id","authority_name")
)
GO
ALTER TABLE "public"."jhi_user_authority" OWNER TO "postgres"
GO
CREATE TABLE "public"."shop"  ( 
	"id"              	bigint NOT NULL,
	"shopid"          	bigint NOT NULL,
	"name"            	varchar(255) NULL,
	"create_date"     	timestamp NULL,
	"last_update_date"	timestamp NULL,
	CONSTRAINT "pk_shop" PRIMARY KEY("id")
)
GO
ALTER TABLE "public"."shop" OWNER TO "hanndbn"
GO
CREATE TABLE "public"."shop_statistic"  ( 
	"id"               	bigint NOT NULL,
	"shopid"           	bigint NOT NULL,
	"cancellation_rate"	bigint NULL,
	"follower_count"   	bigint NULL,
	"preparation_time" 	bigint NULL,
	"rating_bad"       	bigint NULL,
	"rating_good"      	bigint NULL,
	"rating_normal"    	bigint NULL,
	"rating_star"      	real NULL,
	"response_rate"    	bigint NULL,
	"response_time"    	bigint NULL,
	"create_date"      	timestamp NULL,
	"last_update_date" 	timestamp NULL,
	CONSTRAINT "pk_shop_statistic" PRIMARY KEY("id")
)
GO
ALTER TABLE "public"."shop_statistic" OWNER TO "hanndbn"
GO
CREATE INDEX "idx_persistent_audit_event"
	ON "public"."jhi_persistent_audit_event" USING btree (principal, event_date)
GO
CREATE INDEX "idx_persistent_audit_evt_data"
	ON "public"."jhi_persistent_audit_evt_data" USING btree (event_id)
GO

ALTER TABLE "public"."jhi_user"
	ADD CONSTRAINT "ux_user_login"
	UNIQUE ("login")
GO
ALTER TABLE "public"."jhi_user"
	ADD CONSTRAINT "ux_user_email"
	UNIQUE ("email")
GO
ALTER TABLE "public"."jhi_persistent_audit_evt_data"
	ADD CONSTRAINT "fk_evt_pers_audit_evt_data"
	FOREIGN KEY("event_id")
	REFERENCES "public"."jhi_persistent_audit_event"("event_id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "public"."jhi_user_authority"
	ADD CONSTRAINT "fk_user_id"
	FOREIGN KEY("user_id")
	REFERENCES "public"."jhi_user"("id")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "public"."jhi_user_authority"
	ADD CONSTRAINT "fk_authority_name"
	FOREIGN KEY("authority_name")
	REFERENCES "public"."jhi_authority"("name")
	MATCH SIMPLE
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
